import { defineConfig, devices } from '@playwright/test';

/**
 * F8 — Playwright config for L3 visual regression
 * (testing-markdown-rendering.md §Determinism).
 *
 * Every knob that could make pixels vary is pinned here so baselines are
 * reproducible between a dev run and CI:
 *   - Bundled local fonts (Inter / JetBrains Mono via @fontsource) — the harness
 *     imports them, so NO network font fetch happens during a run.
 *   - Fixed 1280×800 viewport, `deviceScaleFactor: 1`, `scale: 'css'`.
 *   - `reducedMotion: 'reduce'` + `animations: 'disabled'` + the harness
 *     `determinism.css` — all motion is frozen.
 *   - Fixed UTC timezone + `en-US` locale.
 *   - Light + dark are two screenshots per fixture, driven by the `?theme` URL
 *     param (the harness toggles F5's `.dark` class).
 *   - `mask` (used per-assertion in the specs) hides dynamic regions such as
 *     timestamps / git hashes.
 *   - Mermaid theme/seed is pinned via a harness global (`__MERMAID_THEME__`),
 *     a placeholder until R2 renders diagrams.
 *
 * Baselines are committed under `test/visual/__screenshots__/` and are only ever
 * regenerated by an explicit, reviewed `--update-snapshots` run — never
 * automatically. Because font rendering is OS-specific, both the committed
 * baselines and CI run inside the SAME pinned Playwright container image
 * (see `.github/workflows/ci.yml`); regenerate with the same image (README in
 * `test/visual/`).
 */
const PORT = 5199;
const BASE_URL = `http://127.0.0.1:${PORT}`;

export default defineConfig({
  testDir: './test/visual',
  // One committed baseline per fixture+theme, shared by every OS that runs in
  // the pinned container. No `{platform}` suffix — the container fixes the OS.
  snapshotPathTemplate:
    'test/visual/__screenshots__/{testFileName}/{projectName}/{arg}{ext}',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI
    ? [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }]]
    : [['list']],
  use: {
    baseURL: BASE_URL,
    viewport: { width: 1280, height: 800 },
    deviceScaleFactor: 1,
    reducedMotion: 'reduce',
    timezoneId: 'UTC',
    locale: 'en-US',
  },
  expect: {
    toHaveScreenshot: {
      // A tiny tolerance absorbs sub-pixel antialiasing noise without hiding
      // real regressions.
      maxDiffPixelRatio: 0.01,
      animations: 'disabled',
      caret: 'hide',
      scale: 'css',
    },
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        deviceScaleFactor: 1,
      },
    },
  ],
  webServer: {
    command: 'npx vite --config test/visual/harness/vite.config.ts',
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
});
